deployment:
  etcd:
    host:
      - "http://127.0.0.1:2379"
    prefix: /aisix
    timeout: 30
    tls:
      ca_file: ca.pem
      cert_file: cert.pem
      key_file: key.pem
      insecure_skip_verify: false
  admin:
    admin_key:
      - key: admin

server:
  proxy:
    listen: 0.0.0.0:3000
    tls:
      enabled: false
      cert_file: cert.pem
      key_file: key.pem
  admin:
    listen: 127.0.0.1:3001
