/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutProvidersIndexRouteImport } from './routes/_layout/providers/index'
import { Route as LayoutPoliciesIndexRouteImport } from './routes/_layout/policies/index'
import { Route as LayoutPlaygroundIndexRouteImport } from './routes/_layout/playground/index'
import { Route as LayoutModelsIndexRouteImport } from './routes/_layout/models/index'
import { Route as LayoutGuardrailsIndexRouteImport } from './routes/_layout/guardrails/index'
import { Route as LayoutApikeysIndexRouteImport } from './routes/_layout/apikeys/index'
import { Route as LayoutProvidersCreateRouteImport } from './routes/_layout/providers/create'
import { Route as LayoutProvidersIdRouteImport } from './routes/_layout/providers/$id'
import { Route as LayoutPoliciesCreateRouteImport } from './routes/_layout/policies/create'
import { Route as LayoutPoliciesIdRouteImport } from './routes/_layout/policies/$id'
import { Route as LayoutModelsCreateRouteImport } from './routes/_layout/models/create'
import { Route as LayoutModelsIdRouteImport } from './routes/_layout/models/$id'
import { Route as LayoutGuardrailsCreateRouteImport } from './routes/_layout/guardrails/create'
import { Route as LayoutGuardrailsIdRouteImport } from './routes/_layout/guardrails/$id'
import { Route as LayoutApikeysCreateRouteImport } from './routes/_layout/apikeys/create'
import { Route as LayoutApikeysIdRouteImport } from './routes/_layout/apikeys/$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersIndexRoute = LayoutProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesIndexRoute = LayoutPoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundIndexRoute = LayoutPlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsIndexRoute = LayoutModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuardrailsIndexRoute = LayoutGuardrailsIndexRouteImport.update({
  id: '/guardrails/',
  path: '/guardrails/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysIndexRoute = LayoutApikeysIndexRouteImport.update({
  id: '/apikeys/',
  path: '/apikeys/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersCreateRoute = LayoutProvidersCreateRouteImport.update({
  id: '/providers/create',
  path: '/providers/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProvidersIdRoute = LayoutProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesCreateRoute = LayoutPoliciesCreateRouteImport.update({
  id: '/policies/create',
  path: '/policies/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPoliciesIdRoute = LayoutPoliciesIdRouteImport.update({
  id: '/policies/$id',
  path: '/policies/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsCreateRoute = LayoutModelsCreateRouteImport.update({
  id: '/models/create',
  path: '/models/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutModelsIdRoute = LayoutModelsIdRouteImport.update({
  id: '/models/$id',
  path: '/models/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuardrailsCreateRoute = LayoutGuardrailsCreateRouteImport.update({
  id: '/guardrails/create',
  path: '/guardrails/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGuardrailsIdRoute = LayoutGuardrailsIdRouteImport.update({
  id: '/guardrails/$id',
  path: '/guardrails/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysCreateRoute = LayoutApikeysCreateRouteImport.update({
  id: '/apikeys/create',
  path: '/apikeys/create',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutApikeysIdRoute = LayoutApikeysIdRouteImport.update({
  id: '/apikeys/$id',
  path: '/apikeys/$id',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof LayoutSettingsRoute
  '/apikeys/$id': typeof LayoutApikeysIdRoute
  '/apikeys/create': typeof LayoutApikeysCreateRoute
  '/guardrails/$id': typeof LayoutGuardrailsIdRoute
  '/guardrails/create': typeof LayoutGuardrailsCreateRoute
  '/models/$id': typeof LayoutModelsIdRoute
  '/models/create': typeof LayoutModelsCreateRoute
  '/policies/$id': typeof LayoutPoliciesIdRoute
  '/policies/create': typeof LayoutPoliciesCreateRoute
  '/providers/$id': typeof LayoutProvidersIdRoute
  '/providers/create': typeof LayoutProvidersCreateRoute
  '/apikeys/': typeof LayoutApikeysIndexRoute
  '/guardrails/': typeof LayoutGuardrailsIndexRoute
  '/models/': typeof LayoutModelsIndexRoute
  '/playground/': typeof LayoutPlaygroundIndexRoute
  '/policies/': typeof LayoutPoliciesIndexRoute
  '/providers/': typeof LayoutProvidersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof LayoutSettingsRoute
  '/apikeys/$id': typeof LayoutApikeysIdRoute
  '/apikeys/create': typeof LayoutApikeysCreateRoute
  '/guardrails/$id': typeof LayoutGuardrailsIdRoute
  '/guardrails/create': typeof LayoutGuardrailsCreateRoute
  '/models/$id': typeof LayoutModelsIdRoute
  '/models/create': typeof LayoutModelsCreateRoute
  '/policies/$id': typeof LayoutPoliciesIdRoute
  '/policies/create': typeof LayoutPoliciesCreateRoute
  '/providers/$id': typeof LayoutProvidersIdRoute
  '/providers/create': typeof LayoutProvidersCreateRoute
  '/apikeys': typeof LayoutApikeysIndexRoute
  '/guardrails': typeof LayoutGuardrailsIndexRoute
  '/models': typeof LayoutModelsIndexRoute
  '/playground': typeof LayoutPlaygroundIndexRoute
  '/policies': typeof LayoutPoliciesIndexRoute
  '/providers': typeof LayoutProvidersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/apikeys/$id': typeof LayoutApikeysIdRoute
  '/_layout/apikeys/create': typeof LayoutApikeysCreateRoute
  '/_layout/guardrails/$id': typeof LayoutGuardrailsIdRoute
  '/_layout/guardrails/create': typeof LayoutGuardrailsCreateRoute
  '/_layout/models/$id': typeof LayoutModelsIdRoute
  '/_layout/models/create': typeof LayoutModelsCreateRoute
  '/_layout/policies/$id': typeof LayoutPoliciesIdRoute
  '/_layout/policies/create': typeof LayoutPoliciesCreateRoute
  '/_layout/providers/$id': typeof LayoutProvidersIdRoute
  '/_layout/providers/create': typeof LayoutProvidersCreateRoute
  '/_layout/apikeys/': typeof LayoutApikeysIndexRoute
  '/_layout/guardrails/': typeof LayoutGuardrailsIndexRoute
  '/_layout/models/': typeof LayoutModelsIndexRoute
  '/_layout/playground/': typeof LayoutPlaygroundIndexRoute
  '/_layout/policies/': typeof LayoutPoliciesIndexRoute
  '/_layout/providers/': typeof LayoutProvidersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/apikeys/$id'
    | '/apikeys/create'
    | '/guardrails/$id'
    | '/guardrails/create'
    | '/models/$id'
    | '/models/create'
    | '/policies/$id'
    | '/policies/create'
    | '/providers/$id'
    | '/providers/create'
    | '/apikeys/'
    | '/guardrails/'
    | '/models/'
    | '/playground/'
    | '/policies/'
    | '/providers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/apikeys/$id'
    | '/apikeys/create'
    | '/guardrails/$id'
    | '/guardrails/create'
    | '/models/$id'
    | '/models/create'
    | '/policies/$id'
    | '/policies/create'
    | '/providers/$id'
    | '/providers/create'
    | '/apikeys'
    | '/guardrails'
    | '/models'
    | '/playground'
    | '/policies'
    | '/providers'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/settings'
    | '/_layout/apikeys/$id'
    | '/_layout/apikeys/create'
    | '/_layout/guardrails/$id'
    | '/_layout/guardrails/create'
    | '/_layout/models/$id'
    | '/_layout/models/create'
    | '/_layout/policies/$id'
    | '/_layout/policies/create'
    | '/_layout/providers/$id'
    | '/_layout/providers/create'
    | '/_layout/apikeys/'
    | '/_layout/guardrails/'
    | '/_layout/models/'
    | '/_layout/playground/'
    | '/_layout/policies/'
    | '/_layout/providers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers/': {
      id: '/_layout/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof LayoutProvidersIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/': {
      id: '/_layout/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof LayoutPoliciesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground/': {
      id: '/_layout/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof LayoutPlaygroundIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/': {
      id: '/_layout/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof LayoutModelsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guardrails/': {
      id: '/_layout/guardrails/'
      path: '/guardrails'
      fullPath: '/guardrails/'
      preLoaderRoute: typeof LayoutGuardrailsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/': {
      id: '/_layout/apikeys/'
      path: '/apikeys'
      fullPath: '/apikeys/'
      preLoaderRoute: typeof LayoutApikeysIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers/create': {
      id: '/_layout/providers/create'
      path: '/providers/create'
      fullPath: '/providers/create'
      preLoaderRoute: typeof LayoutProvidersCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/providers/$id': {
      id: '/_layout/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof LayoutProvidersIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/create': {
      id: '/_layout/policies/create'
      path: '/policies/create'
      fullPath: '/policies/create'
      preLoaderRoute: typeof LayoutPoliciesCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/policies/$id': {
      id: '/_layout/policies/$id'
      path: '/policies/$id'
      fullPath: '/policies/$id'
      preLoaderRoute: typeof LayoutPoliciesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/create': {
      id: '/_layout/models/create'
      path: '/models/create'
      fullPath: '/models/create'
      preLoaderRoute: typeof LayoutModelsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/models/$id': {
      id: '/_layout/models/$id'
      path: '/models/$id'
      fullPath: '/models/$id'
      preLoaderRoute: typeof LayoutModelsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guardrails/create': {
      id: '/_layout/guardrails/create'
      path: '/guardrails/create'
      fullPath: '/guardrails/create'
      preLoaderRoute: typeof LayoutGuardrailsCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/guardrails/$id': {
      id: '/_layout/guardrails/$id'
      path: '/guardrails/$id'
      fullPath: '/guardrails/$id'
      preLoaderRoute: typeof LayoutGuardrailsIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/create': {
      id: '/_layout/apikeys/create'
      path: '/apikeys/create'
      fullPath: '/apikeys/create'
      preLoaderRoute: typeof LayoutApikeysCreateRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/apikeys/$id': {
      id: '/_layout/apikeys/$id'
      path: '/apikeys/$id'
      fullPath: '/apikeys/$id'
      preLoaderRoute: typeof LayoutApikeysIdRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutApikeysIdRoute: typeof LayoutApikeysIdRoute
  LayoutApikeysCreateRoute: typeof LayoutApikeysCreateRoute
  LayoutGuardrailsIdRoute: typeof LayoutGuardrailsIdRoute
  LayoutGuardrailsCreateRoute: typeof LayoutGuardrailsCreateRoute
  LayoutModelsIdRoute: typeof LayoutModelsIdRoute
  LayoutModelsCreateRoute: typeof LayoutModelsCreateRoute
  LayoutPoliciesIdRoute: typeof LayoutPoliciesIdRoute
  LayoutPoliciesCreateRoute: typeof LayoutPoliciesCreateRoute
  LayoutProvidersIdRoute: typeof LayoutProvidersIdRoute
  LayoutProvidersCreateRoute: typeof LayoutProvidersCreateRoute
  LayoutApikeysIndexRoute: typeof LayoutApikeysIndexRoute
  LayoutGuardrailsIndexRoute: typeof LayoutGuardrailsIndexRoute
  LayoutModelsIndexRoute: typeof LayoutModelsIndexRoute
  LayoutPlaygroundIndexRoute: typeof LayoutPlaygroundIndexRoute
  LayoutPoliciesIndexRoute: typeof LayoutPoliciesIndexRoute
  LayoutProvidersIndexRoute: typeof LayoutProvidersIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutApikeysIdRoute: LayoutApikeysIdRoute,
  LayoutApikeysCreateRoute: LayoutApikeysCreateRoute,
  LayoutGuardrailsIdRoute: LayoutGuardrailsIdRoute,
  LayoutGuardrailsCreateRoute: LayoutGuardrailsCreateRoute,
  LayoutModelsIdRoute: LayoutModelsIdRoute,
  LayoutModelsCreateRoute: LayoutModelsCreateRoute,
  LayoutPoliciesIdRoute: LayoutPoliciesIdRoute,
  LayoutPoliciesCreateRoute: LayoutPoliciesCreateRoute,
  LayoutProvidersIdRoute: LayoutProvidersIdRoute,
  LayoutProvidersCreateRoute: LayoutProvidersCreateRoute,
  LayoutApikeysIndexRoute: LayoutApikeysIndexRoute,
  LayoutGuardrailsIndexRoute: LayoutGuardrailsIndexRoute,
  LayoutModelsIndexRoute: LayoutModelsIndexRoute,
  LayoutPlaygroundIndexRoute: LayoutPlaygroundIndexRoute,
  LayoutPoliciesIndexRoute: LayoutPoliciesIndexRoute,
  LayoutProvidersIndexRoute: LayoutProvidersIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
